/* Generated by Yosys 0.51 (git sha1 c4b519022, clang++ 10.0.0-4ubuntu1 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "DekatronCounter" *)
(* src = "../DekatronPC/Dekatron/DekatronCounter.sv:1.1-218.10" *)
module \$paramod\DekatronCounter\D_NUM=32'00000000000000000000000000000100\WRITE=1'0 (Rst_n, Clk, hsClk, Request, Dec, Set, SetZero, In, Ready, Zero, Out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:12.13-12.16" *)
  input Clk;
  wire Clk;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:22.16-22.19" *)
  input Dec;
  wire Dec;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:26.28-26.30" *)
  input [15:0] In;
  wire [15:0] In;
  wire [2:0] Nines;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:30.26-30.29" *)
  output [15:0] Out;
  wire [15:0] Out;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:126.6-126.12" *)
  wire PulseF;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:125.6-125.12" *)
  wire PulseR;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:127.12-127.18" *)
  wire [1:0] Pulses;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:28.17-28.22" *)
  output Ready;
  wire Ready;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:21.13-21.20" *)
  input Request;
  wire Request;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:11.13-11.18" *)
  input Rst_n;
  wire Rst_n;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:23.16-23.19" *)
  input Set;
  wire Set;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:67.6-67.12" *)
  wire SetTop;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:159.12-159.22" *)
  wire [2:0] SetTopZero;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:24.13-24.20" *)
  input SetZero;
  wire SetZero;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:68.6-68.16" *)
  wire SetZeroInt;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:45.18-45.24" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] TopOut;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:29.17-29.21" *)
  output Zero;
  wire Zero;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:42.17-42.23" *)
  wire [3:0] Zeroes;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:33.6-33.14" *)
  wire _Request;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:180.7-180.14" *)
  wire \dek[0].DekNine ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:179.7-179.14" *)
  wire \dek[0].DekZero ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:181.7-181.12" *)
  (* unused_bits = "0" *)
  wire \dek[0].Equal ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:171.13-171.20" *)
  wire [1:0] \dek[0].npulses ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:169.13-169.19" *)
  wire [1:0] \dek[0].pulses ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:180.7-180.14" *)
  wire \dek[1].DekNine ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:179.7-179.14" *)
  wire \dek[1].DekZero ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:181.7-181.12" *)
  (* unused_bits = "0" *)
  wire \dek[1].Equal ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:171.13-171.20" *)
  wire [1:0] \dek[1].npulses ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:169.13-169.19" *)
  wire [1:0] \dek[1].pulses ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:180.7-180.14" *)
  wire \dek[2].DekNine ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:179.7-179.14" *)
  wire \dek[2].DekZero ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:181.7-181.12" *)
  (* unused_bits = "0" *)
  wire \dek[2].Equal ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:171.13-171.20" *)
  wire [1:0] \dek[2].npulses ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:169.13-169.19" *)
  wire [1:0] \dek[2].pulses ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:180.7-180.14" *)
  (* unused_bits = "0" *)
  wire \dek[3].DekNine ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:179.7-179.14" *)
  wire \dek[3].DekZero ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:181.7-181.12" *)
  (* unused_bits = "0" *)
  wire \dek[3].Equal ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:169.13-169.19" *)
  wire [1:0] \dek[3].pulses ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:15.13-15.18" *)
  input hsClk;
  wire hsClk;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:60.18-60.22" *)
  wire [2:0] next;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:60.11-60.16" *)
  wire [2:0] state;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:142.6-142.15" *)
  wire write_set;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:150.6-150.14" *)
  wire writed_n;
  NOT_6N16B _33_ (
    .A(Zeroes[2]),
    .Y(_00_)
  );
  NOT_6N16B _34_ (
    .A(state[2]),
    .Y(_01_)
  );
  NOT_6N16B _35_ (
    .A(state[1]),
    .Y(_02_)
  );
  NOT_6N16B _36_ (
    .A(state[0]),
    .Y(_03_)
  );
  NOT_6N16B _37_ (
    .A(Pulses[0]),
    .Y(_04_)
  );
  NOT_6N16B _38_ (
    .A(Pulses[1]),
    .Y(_05_)
  );
  NOT_6N16B _39_ (
    .A(Nines[2]),
    .Y(_06_)
  );
  NOT_6N16B _40_ (
    .A(_Request),
    .Y(_07_)
  );
  NOT_6N16B _41_ (
    .A(Set),
    .Y(_08_)
  );
  NAND2_J2 _42_ (
    .A(Zeroes[3]),
    .B(Zeroes[2]),
    .Y(_09_)
  );
  NAND2_J2 _43_ (
    .A(Zeroes[0]),
    .B(Zeroes[1]),
    .Y(_10_)
  );
  NOR2_N16 _44_ (
    .A(_09_),
    .B(_10_),
    .Y(Zero)
  );
  AND2_N16X7 _45_ (
    .A(state[2]),
    .B(writed_n),
    .Y(_11_)
  );
  AND2_N16X7 _46_ (
    .A(state[0]),
    .B(_11_),
    .Y(_12_)
  );
  AND2_N16X7 _47_ (
    .A(_02_),
    .B(_12_),
    .Y(SetTopZero[0])
  );
  NAND2_J2 _48_ (
    .A(state[1]),
    .B(_11_),
    .Y(_13_)
  );
  NOR2_N16 _49_ (
    .A(state[0]),
    .B(_13_),
    .Y(SetTopZero[1])
  );
  NOR2_N16 _50_ (
    .A(_03_),
    .B(_13_),
    .Y(SetTopZero[2])
  );
  NAND2_J2 _51_ (
    .A(_01_),
    .B(state[1]),
    .Y(_14_)
  );
  NOR2_N16 _52_ (
    .A(state[0]),
    .B(_14_),
    .Y(PulseF)
  );
  NAND4_N16X7 _53_ (
    .A(_01_),
    .B(state[1]),
    .C(_03_),
    .D(Nines[0]),
    .Y(_15_)
  );
  NOR2_N16 _54_ (
    .A(_03_),
    .B(_14_),
    .Y(PulseR)
  );
  NAND4_N16X7 _55_ (
    .A(_01_),
    .B(state[1]),
    .C(state[0]),
    .D(Zeroes[0]),
    .Y(_16_)
  );
  AND2_N16X7 _56_ (
    .A(_15_),
    .B(_16_),
    .Y(_17_)
  );
  A1OOI_N16X7 _57_ (
    .A(_15_),
    .B(_16_),
    .C(_04_),
    .Y(\dek[1].pulses [0])
  );
  A1OOI_N16X7 _58_ (
    .A(_15_),
    .B(_16_),
    .C(_05_),
    .Y(\dek[1].pulses [1])
  );
  NAND4_N16X7 _59_ (
    .A(_01_),
    .B(state[1]),
    .C(_03_),
    .D(Nines[1]),
    .Y(_18_)
  );
  NAND4_N16X7 _60_ (
    .A(_01_),
    .B(state[1]),
    .C(state[0]),
    .D(Zeroes[1]),
    .Y(_19_)
  );
  AND2_N16X7 _61_ (
    .A(_18_),
    .B(_19_),
    .Y(_20_)
  );
  NAND2_J2 _62_ (
    .A(_18_),
    .B(_19_),
    .Y(_21_)
  );
  AND2_N16X7 _63_ (
    .A(\dek[1].pulses [0]),
    .B(_21_),
    .Y(\dek[2].pulses [0])
  );
  AND2_N16X7 _64_ (
    .A(\dek[1].pulses [1]),
    .B(_21_),
    .Y(\dek[2].pulses [1])
  );
  NOR4_N16 _65_ (
    .A(state[2]),
    .B(_02_),
    .C(state[0]),
    .D(_06_),
    .Y(_22_)
  );
  NOR4_N16 _66_ (
    .A(_00_),
    .B(state[2]),
    .C(_02_),
    .D(_03_),
    .Y(_23_)
  );
  NOR2_N16 _67_ (
    .A(_22_),
    .B(_23_),
    .Y(_24_)
  );
  NOR4_N16 _68_ (
    .A(_04_),
    .B(_17_),
    .C(_20_),
    .D(_24_),
    .Y(\dek[3].pulses [0])
  );
  NOR4_N16 _69_ (
    .A(_05_),
    .B(_17_),
    .C(_20_),
    .D(_24_),
    .Y(\dek[3].pulses [1])
  );
  OR2_N16 _70_ (
    .A(state[2]),
    .B(state[0]),
    .Y(_25_)
  );
  NOR4_N16 _71_ (
    .A(state[2]),
    .B(state[1]),
    .C(state[0]),
    .D(_07_),
    .Y(_26_)
  );
  NAND2_J2 _72_ (
    .A(Dec),
    .B(_26_),
    .Y(_27_)
  );
  OR2_N16 _73_ (
    .A(SetZero),
    .B(Set),
    .Y(_28_)
  );
  A1OOI_N16X7 _74_ (
    .A(_26_),
    .B(_28_),
    .C(_12_),
    .Y(_29_)
  );
  NAND2_J2 _75_ (
    .A(_27_),
    .B(_29_),
    .Y(next[0])
  );
  NAND2_J2 _76_ (
    .A(SetZero),
    .B(_08_),
    .Y(_30_)
  );
  NAND2_J2 _77_ (
    .A(_26_),
    .B(_30_),
    .Y(_31_)
  );
  NAND2_J2 _78_ (
    .A(_13_),
    .B(_31_),
    .Y(next[1])
  );
  NAND2_J2 _79_ (
    .A(_13_),
    .B(_29_),
    .Y(next[2])
  );
  OR2_N16 _80_ (
    .A(Pulses[1]),
    .B(Request),
    .Y(_32_)
  );
  NOR4_N16 _81_ (
    .A(state[1]),
    .B(Pulses[0]),
    .C(_25_),
    .D(_32_),
    .Y(Ready)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:202.2-211.5" *)
  DFFSR_n _82_ (
    .C(Clk),
    .D(\dek[1].DekNine ),
    .Q(Nines[1]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:202.2-211.5" *)
  DFFSR_n _83_ (
    .C(Clk),
    .D(\dek[1].DekZero ),
    .Q(Zeroes[1]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:202.2-211.5" *)
  DFFSR_n _84_ (
    .C(Clk),
    .D(\dek[2].DekNine ),
    .Q(Nines[2]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:202.2-211.5" *)
  DFFSR_n _85_ (
    .C(Clk),
    .D(\dek[2].DekZero ),
    .Q(Zeroes[2]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:202.2-211.5" *)
  DFFSR_n _86_ (
    .C(Clk),
    .D(\dek[0].DekZero ),
    .Q(Zeroes[0]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:202.2-211.5" *)
  DFFSR_n _87_ (
    .C(Clk),
    .D(\dek[3].DekZero ),
    .Q(Zeroes[3]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:62.1-65.4" *)
  DFFSR_n _88_ (
    .C(Clk),
    .D(next[0]),
    .Q(state[0]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:62.1-65.4" *)
  DFFSR_n _89_ (
    .C(Clk),
    .D(next[1]),
    .Q(state[1]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:62.1-65.4" *)
  DFFSR_n _90_ (
    .C(Clk),
    .D(next[2]),
    .Q(state[2]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:202.2-211.5" *)
  DFFSR_n _91_ (
    .C(Clk),
    .D(\dek[0].DekNine ),
    .Q(Nines[0]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:187.3-199.3" *)
  \$paramod\DekatronModule\READ=1'1\WRITE=1'0\TOP_LIMIT_MODE=1'0\TOP_PIN_OUT=4'0101  \dek[0].dModule  (
    .Equal(\dek[0].Equal ),
    .In(In[3:0]),
    .Nine(\dek[0].DekNine ),
    .Out(Out[3:0]),
    .PulseF(Pulses[0]),
    .PulseR(Pulses[1]),
    .Rst_n(Rst_n),
    .Set(SetTopZero),
    .TopPin(TopOut[0]),
    .Zero(\dek[0].DekZero ),
    .hsClk(hsClk)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:187.3-199.3" *)
  \$paramod\DekatronModule\READ=1'1\WRITE=1'0\TOP_LIMIT_MODE=1'0\TOP_PIN_OUT=4'0101  \dek[1].dModule  (
    .Equal(\dek[1].Equal ),
    .In(In[7:4]),
    .Nine(\dek[1].DekNine ),
    .Out(Out[7:4]),
    .PulseF(\dek[1].pulses [0]),
    .PulseR(\dek[1].pulses [1]),
    .Rst_n(Rst_n),
    .Set(SetTopZero),
    .TopPin(TopOut[1]),
    .Zero(\dek[1].DekZero ),
    .hsClk(hsClk)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:187.3-199.3" *)
  \$paramod\DekatronModule\READ=1'1\WRITE=1'0\TOP_LIMIT_MODE=1'0\TOP_PIN_OUT=4'0101  \dek[2].dModule  (
    .Equal(\dek[2].Equal ),
    .In(In[11:8]),
    .Nine(\dek[2].DekNine ),
    .Out(Out[11:8]),
    .PulseF(\dek[2].pulses [0]),
    .PulseR(\dek[2].pulses [1]),
    .Rst_n(Rst_n),
    .Set(SetTopZero),
    .TopPin(TopOut[2]),
    .Zero(\dek[2].DekZero ),
    .hsClk(hsClk)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:187.3-199.3" *)
  \$paramod\DekatronModule\READ=1'1\WRITE=1'0\TOP_LIMIT_MODE=1'0\TOP_PIN_OUT=4'0000  \dek[3].dModule  (
    .Equal(\dek[3].Equal ),
    .In(In[15:12]),
    .Nine(\dek[3].DekNine ),
    .Out(Out[15:12]),
    .PulseF(\dek[3].pulses [0]),
    .PulseR(\dek[3].pulses [1]),
    .Rst_n(Rst_n),
    .Set(SetTopZero),
    .TopPin(TopOut[3]),
    .Zero(\dek[3].DekZero ),
    .hsClk(hsClk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:128.9-133.3" *)
  Impulse pulsesImpDec (
    .Clk(Clk),
    .En(PulseR),
    .Impulse(Pulses[1]),
    .Rst_n(Rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:135.9-140.3" *)
  Impulse pulsesImpInc (
    .Clk(Clk),
    .En(PulseF),
    .Impulse(Pulses[0]),
    .Rst_n(Rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:35.9-40.2" *)
  Impulse reqPulse (
    .Clk(Clk),
    .En(Request),
    .Impulse(_Request),
    .Rst_n(Rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:152.2-157.2" *)
  OneShot #(
    .DELAY(32'sd100)
  ) writeOneShot (
    .Clk(hsClk),
    .En(write_set),
    .Impulse(writed_n),
    .Rst_n(Rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:143.9-148.3" *)
  Impulse writeimpulse (
    .Clk(Clk),
    .En(state[2]),
    .Impulse(write_set),
    .Rst_n(Rst_n)
  );
  assign SetTop = 1'h0;
  assign SetZeroInt = 1'h0;
  assign \dek[0].npulses  = \dek[1].pulses ;
  assign \dek[0].pulses  = Pulses;
  assign \dek[1].npulses  = \dek[2].pulses ;
  assign \dek[2].npulses  = \dek[3].pulses ;
endmodule

(* dynports =  1  *)
(* hdlname = "DekatronCounter" *)
(* src = "../DekatronPC/Dekatron/DekatronCounter.sv:1.1-218.10" *)
module \$paramod\DekatronCounter\D_NUM=4'0011\READ=1'0\WRITE=1'0 (Rst_n, Clk, hsClk, Request, Dec, Set, SetZero, In, Ready, Zero, Out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:12.13-12.16" *)
  input Clk;
  wire Clk;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:22.16-22.19" *)
  input Dec;
  wire Dec;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:26.28-26.30" *)
  input [11:0] In;
  wire [11:0] In;
  wire [1:0] Nines;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:30.26-30.29" *)
  output [11:0] Out;
  wire [11:0] Out;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:126.6-126.12" *)
  wire PulseF;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:125.6-125.12" *)
  wire PulseR;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:127.12-127.18" *)
  wire [1:0] Pulses;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:28.17-28.22" *)
  output Ready;
  wire Ready;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:21.13-21.20" *)
  input Request;
  wire Request;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:11.13-11.18" *)
  input Rst_n;
  wire Rst_n;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:23.16-23.19" *)
  input Set;
  wire Set;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:67.6-67.12" *)
  wire SetTop;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:159.12-159.22" *)
  wire [2:0] SetTopZero;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:24.13-24.20" *)
  input SetZero;
  wire SetZero;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:68.6-68.16" *)
  wire SetZeroInt;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:45.18-45.24" *)
  (* unused_bits = "0 1 2" *)
  wire [2:0] TopOut;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:29.17-29.21" *)
  output Zero;
  wire Zero;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:42.17-42.23" *)
  wire [2:0] Zeroes;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:33.6-33.14" *)
  wire _Request;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:180.7-180.14" *)
  wire \dek[0].DekNine ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:179.7-179.14" *)
  wire \dek[0].DekZero ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:181.7-181.12" *)
  (* unused_bits = "0" *)
  wire \dek[0].Equal ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:171.13-171.20" *)
  wire [1:0] \dek[0].npulses ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:169.13-169.19" *)
  wire [1:0] \dek[0].pulses ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:180.7-180.14" *)
  wire \dek[1].DekNine ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:179.7-179.14" *)
  wire \dek[1].DekZero ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:181.7-181.12" *)
  (* unused_bits = "0" *)
  wire \dek[1].Equal ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:171.13-171.20" *)
  wire [1:0] \dek[1].npulses ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:169.13-169.19" *)
  wire [1:0] \dek[1].pulses ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:180.7-180.14" *)
  (* unused_bits = "0" *)
  wire \dek[2].DekNine ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:179.7-179.14" *)
  wire \dek[2].DekZero ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:181.7-181.12" *)
  (* unused_bits = "0" *)
  wire \dek[2].Equal ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:169.13-169.19" *)
  wire [1:0] \dek[2].pulses ;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:15.13-15.18" *)
  input hsClk;
  wire hsClk;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:60.18-60.22" *)
  wire [2:0] next;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:60.11-60.16" *)
  wire [2:0] state;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:142.6-142.15" *)
  wire write_set;
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:150.6-150.14" *)
  wire writed_n;
  NOT_6N16B _26_ (
    .A(state[2]),
    .Y(_00_)
  );
  NOT_6N16B _27_ (
    .A(state[0]),
    .Y(_01_)
  );
  NOT_6N16B _28_ (
    .A(Pulses[0]),
    .Y(_02_)
  );
  NOT_6N16B _29_ (
    .A(Pulses[1]),
    .Y(_03_)
  );
  NOT_6N16B _30_ (
    .A(Zeroes[1]),
    .Y(_04_)
  );
  NOT_6N16B _31_ (
    .A(_Request),
    .Y(_05_)
  );
  NOT_6N16B _32_ (
    .A(Set),
    .Y(_06_)
  );
  NAND2_J2 _33_ (
    .A(Zeroes[2]),
    .B(Zeroes[0]),
    .Y(_07_)
  );
  NOR2_N16 _34_ (
    .A(_04_),
    .B(_07_),
    .Y(Zero)
  );
  AND2_N16X7 _35_ (
    .A(state[2]),
    .B(writed_n),
    .Y(_08_)
  );
  AND2_N16X7 _36_ (
    .A(state[0]),
    .B(_08_),
    .Y(_09_)
  );
  NAND2_J2 _37_ (
    .A(state[0]),
    .B(_08_),
    .Y(_10_)
  );
  NOR2_N16 _38_ (
    .A(state[1]),
    .B(_10_),
    .Y(SetTopZero[0])
  );
  NAND2_J2 _39_ (
    .A(state[1]),
    .B(_08_),
    .Y(_11_)
  );
  NOR2_N16 _40_ (
    .A(state[0]),
    .B(_11_),
    .Y(SetTopZero[1])
  );
  NOR2_N16 _41_ (
    .A(_01_),
    .B(_11_),
    .Y(SetTopZero[2])
  );
  NAND2_J2 _42_ (
    .A(_00_),
    .B(state[1]),
    .Y(_12_)
  );
  NOR2_N16 _43_ (
    .A(state[0]),
    .B(_12_),
    .Y(PulseF)
  );
  NAND4_N16X7 _44_ (
    .A(_00_),
    .B(state[1]),
    .C(_01_),
    .D(Nines[0]),
    .Y(_13_)
  );
  NOR2_N16 _45_ (
    .A(_01_),
    .B(_12_),
    .Y(PulseR)
  );
  NAND4_N16X7 _46_ (
    .A(_00_),
    .B(state[1]),
    .C(state[0]),
    .D(Zeroes[0]),
    .Y(_14_)
  );
  A1OOI_N16X7 _47_ (
    .A(_13_),
    .B(_14_),
    .C(_02_),
    .Y(\dek[1].pulses [0])
  );
  A1OOI_N16X7 _48_ (
    .A(_13_),
    .B(_14_),
    .C(_03_),
    .Y(\dek[1].pulses [1])
  );
  NAND4_N16X7 _49_ (
    .A(_00_),
    .B(state[1]),
    .C(_01_),
    .D(Nines[1]),
    .Y(_15_)
  );
  NAND4_N16X7 _50_ (
    .A(_00_),
    .B(state[1]),
    .C(state[0]),
    .D(Zeroes[1]),
    .Y(_16_)
  );
  NAND2_J2 _51_ (
    .A(_15_),
    .B(_16_),
    .Y(_17_)
  );
  AND2_N16X7 _52_ (
    .A(\dek[1].pulses [0]),
    .B(_17_),
    .Y(\dek[2].pulses [0])
  );
  AND2_N16X7 _53_ (
    .A(\dek[1].pulses [1]),
    .B(_17_),
    .Y(\dek[2].pulses [1])
  );
  OR2_N16 _54_ (
    .A(state[2]),
    .B(state[0]),
    .Y(_18_)
  );
  NOR4_N16 _55_ (
    .A(state[2]),
    .B(state[1]),
    .C(state[0]),
    .D(_05_),
    .Y(_19_)
  );
  NAND2_J2 _56_ (
    .A(Dec),
    .B(_19_),
    .Y(_20_)
  );
  OR2_N16 _57_ (
    .A(Set),
    .B(SetZero),
    .Y(_21_)
  );
  A1OOI_N16X7 _58_ (
    .A(_19_),
    .B(_21_),
    .C(_09_),
    .Y(_22_)
  );
  NAND2_J2 _59_ (
    .A(_20_),
    .B(_22_),
    .Y(next[0])
  );
  NAND2_J2 _60_ (
    .A(_06_),
    .B(SetZero),
    .Y(_23_)
  );
  NAND2_J2 _61_ (
    .A(_19_),
    .B(_23_),
    .Y(_24_)
  );
  NAND2_J2 _62_ (
    .A(_11_),
    .B(_24_),
    .Y(next[1])
  );
  NAND2_J2 _63_ (
    .A(_11_),
    .B(_22_),
    .Y(next[2])
  );
  OR2_N16 _64_ (
    .A(Pulses[1]),
    .B(Request),
    .Y(_25_)
  );
  NOR4_N16 _65_ (
    .A(state[1]),
    .B(Pulses[0]),
    .C(_18_),
    .D(_25_),
    .Y(Ready)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:202.2-211.5" *)
  DFFSR_n _66_ (
    .C(Clk),
    .D(\dek[1].DekZero ),
    .Q(Zeroes[1]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:202.2-211.5" *)
  DFFSR_n _67_ (
    .C(Clk),
    .D(\dek[2].DekZero ),
    .Q(Zeroes[2]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:62.1-65.4" *)
  DFFSR_n _68_ (
    .C(Clk),
    .D(next[0]),
    .Q(state[0]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:62.1-65.4" *)
  DFFSR_n _69_ (
    .C(Clk),
    .D(next[1]),
    .Q(state[1]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:62.1-65.4" *)
  DFFSR_n _70_ (
    .C(Clk),
    .D(next[2]),
    .Q(state[2]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:202.2-211.5" *)
  DFFSR_n _71_ (
    .C(Clk),
    .D(\dek[0].DekNine ),
    .Q(Nines[0]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:202.2-211.5" *)
  DFFSR_n _72_ (
    .C(Clk),
    .D(\dek[0].DekZero ),
    .Q(Zeroes[0]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:202.2-211.5" *)
  DFFSR_n _73_ (
    .C(Clk),
    .D(\dek[1].DekNine ),
    .Q(Nines[1]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:187.3-199.3" *)
  \$paramod\DekatronModule\READ=1'0\WRITE=1'0\TOP_LIMIT_MODE=1'0\TOP_PIN_OUT=4'0101  \dek[0].dModule  (
    .Equal(\dek[0].Equal ),
    .In(In[3:0]),
    .Nine(\dek[0].DekNine ),
    .Out(Out[3:0]),
    .PulseF(Pulses[0]),
    .PulseR(Pulses[1]),
    .Rst_n(Rst_n),
    .Set(SetTopZero),
    .TopPin(TopOut[0]),
    .Zero(\dek[0].DekZero ),
    .hsClk(hsClk)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:187.3-199.3" *)
  \$paramod\DekatronModule\READ=1'0\WRITE=1'0\TOP_LIMIT_MODE=1'0\TOP_PIN_OUT=4'0101  \dek[1].dModule  (
    .Equal(\dek[1].Equal ),
    .In(In[7:4]),
    .Nine(\dek[1].DekNine ),
    .Out(Out[7:4]),
    .PulseF(\dek[1].pulses [0]),
    .PulseR(\dek[1].pulses [1]),
    .Rst_n(Rst_n),
    .Set(SetTopZero),
    .TopPin(TopOut[1]),
    .Zero(\dek[1].DekZero ),
    .hsClk(hsClk)
  );
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:187.3-199.3" *)
  \$paramod\DekatronModule\READ=1'0\WRITE=1'0\TOP_LIMIT_MODE=1'0\TOP_PIN_OUT=4'0101  \dek[2].dModule  (
    .Equal(\dek[2].Equal ),
    .In(In[11:8]),
    .Nine(\dek[2].DekNine ),
    .Out(Out[11:8]),
    .PulseF(\dek[2].pulses [0]),
    .PulseR(\dek[2].pulses [1]),
    .Rst_n(Rst_n),
    .Set(SetTopZero),
    .TopPin(TopOut[2]),
    .Zero(\dek[2].DekZero ),
    .hsClk(hsClk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:128.9-133.3" *)
  Impulse pulsesImpDec (
    .Clk(Clk),
    .En(PulseR),
    .Impulse(Pulses[1]),
    .Rst_n(Rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:135.9-140.3" *)
  Impulse pulsesImpInc (
    .Clk(Clk),
    .En(PulseF),
    .Impulse(Pulses[0]),
    .Rst_n(Rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:35.9-40.2" *)
  Impulse reqPulse (
    .Clk(Clk),
    .En(Request),
    .Impulse(_Request),
    .Rst_n(Rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:152.2-157.2" *)
  OneShot #(
    .DELAY(32'sd100)
  ) writeOneShot (
    .Clk(hsClk),
    .En(write_set),
    .Impulse(writed_n),
    .Rst_n(Rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronCounter.sv:143.9-148.3" *)
  Impulse writeimpulse (
    .Clk(Clk),
    .En(state[2]),
    .Impulse(write_set),
    .Rst_n(Rst_n)
  );
  assign SetTop = 1'h0;
  assign SetZeroInt = 1'h0;
  assign \dek[0].npulses  = \dek[1].pulses ;
  assign \dek[0].pulses  = Pulses;
  assign \dek[1].npulses  = \dek[2].pulses ;
endmodule

(* hdlname = "DekatronModule" *)
(* keep_hierarchy = "yes" *)
(* src = "../DekatronPC/Dekatron/DekatronModule.sv:1.30-99.10" *)
module \$paramod\DekatronModule\READ=1'0\WRITE=1'0\TOP_LIMIT_MODE=1'0\TOP_PIN_OUT=4'0101 (Rst_n, hsClk, In, Set, PulseF, PulseR, Out, Equal, Zero, TopPin, Nine);
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:17.17-17.22" *)
  output Equal;
  wire Equal;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:10.21-10.23" *)
  input [3:0] In;
  wire [3:0] In;
  wire InPosDek_n;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:21.17-21.21" *)
  output Nine;
  wire Nine;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:16.22-16.25" *)
  output [3:0] Out;
  wire [3:0] Out;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:24.11-24.17" *)
  (* unused_bits = "1 2 3 4 6 7 8" *)
  wire [9:0] OutPos;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:13.16-13.22" *)
  input PulseF;
  wire PulseF;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:14.16-14.22" *)
  input PulseR;
  wire PulseR;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:62.12-62.18" *)
  wire [1:0] Pulses;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:7.16-7.21" *)
  input Rst_n;
  wire Rst_n;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:11.22-11.25" *)
  input [2:0] Set;
  wire [2:0] Set;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:20.17-20.23" *)
  output TopPin;
  wire TopPin;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:19.17-19.21" *)
  output Zero;
  wire Zero;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:25.11-25.18" *)
  (* unused_bits = "1 2 3 4 6 7 8" *)
  wire [9:0] _OutPos;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:8.16-8.21" *)
  input hsClk;
  wire hsClk;
  NOT_6N16B _0_ (
    .A(Set[0]),
    .Y(InPosDek_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:74.10-80.2" *)
  Dekatron dekatron (
    .In_n({ 9'h1ff, InPosDek_n }),
    .Out(_OutPos),
    .Pulses(Pulses),
    .Rst_n(Rst_n),
    .hsClk(hsClk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:66.21-72.2" *)
  DekatronPulseSender pulseSender (
    .PulseF(PulseF),
    .PulseR(PulseR),
    .Pulses(Pulses),
    .Rst_n(Rst_n),
    .hsClk(hsClk)
  );
  assign Equal = 1'hx;
  assign Nine = _OutPos[9];
  assign Out = 4'hx;
  assign OutPos = _OutPos;
  assign TopPin = _OutPos[5];
  assign Zero = _OutPos[0];
endmodule

(* hdlname = "DekatronModule" *)
(* keep_hierarchy = "yes" *)
(* src = "../DekatronPC/Dekatron/DekatronModule.sv:1.30-99.10" *)
module \$paramod\DekatronModule\READ=1'1\WRITE=1'0\TOP_LIMIT_MODE=1'0\TOP_PIN_OUT=4'0000 (Rst_n, hsClk, In, Set, PulseF, PulseR, Out, Equal, Zero, TopPin, Nine);
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:17.17-17.22" *)
  output Equal;
  wire Equal;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:10.21-10.23" *)
  input [3:0] In;
  wire [3:0] In;
  wire InPosDek_n;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:21.17-21.21" *)
  output Nine;
  wire Nine;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:16.22-16.25" *)
  output [3:0] Out;
  wire [3:0] Out;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:24.11-24.17" *)
  wire [9:0] OutPos;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:13.16-13.22" *)
  input PulseF;
  wire PulseF;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:14.16-14.22" *)
  input PulseR;
  wire PulseR;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:62.12-62.18" *)
  wire [1:0] Pulses;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:7.16-7.21" *)
  input Rst_n;
  wire Rst_n;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:11.22-11.25" *)
  input [2:0] Set;
  wire [2:0] Set;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:20.17-20.23" *)
  output TopPin;
  wire TopPin;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:19.17-19.21" *)
  output Zero;
  wire Zero;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:25.11-25.18" *)
  wire [9:0] _OutPos;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:8.16-8.21" *)
  input hsClk;
  wire hsClk;
  NOT_6N16B _0_ (
    .A(Set[0]),
    .Y(InPosDek_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:85.14-88.6" *)
  BinToBcd \Reading.binToDbc  (
    .In(OutPos),
    .Out(Out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:74.10-80.2" *)
  Dekatron dekatron (
    .In_n({ 9'h1ff, InPosDek_n }),
    .Out(OutPos),
    .Pulses(Pulses),
    .Rst_n(Rst_n),
    .hsClk(hsClk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:66.21-72.2" *)
  DekatronPulseSender pulseSender (
    .PulseF(PulseF),
    .PulseR(PulseR),
    .Pulses(Pulses),
    .Rst_n(Rst_n),
    .hsClk(hsClk)
  );
  assign Equal = 1'hx;
  assign Nine = OutPos[9];
  assign TopPin = OutPos[0];
  assign Zero = OutPos[0];
  assign _OutPos = OutPos;
endmodule

(* hdlname = "DekatronModule" *)
(* keep_hierarchy = "yes" *)
(* src = "../DekatronPC/Dekatron/DekatronModule.sv:1.30-99.10" *)
module \$paramod\DekatronModule\READ=1'1\WRITE=1'0\TOP_LIMIT_MODE=1'0\TOP_PIN_OUT=4'0101 (Rst_n, hsClk, In, Set, PulseF, PulseR, Out, Equal, Zero, TopPin, Nine);
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:17.17-17.22" *)
  output Equal;
  wire Equal;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:10.21-10.23" *)
  input [3:0] In;
  wire [3:0] In;
  wire InPosDek_n;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:21.17-21.21" *)
  output Nine;
  wire Nine;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:16.22-16.25" *)
  output [3:0] Out;
  wire [3:0] Out;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:24.11-24.17" *)
  wire [9:0] OutPos;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:13.16-13.22" *)
  input PulseF;
  wire PulseF;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:14.16-14.22" *)
  input PulseR;
  wire PulseR;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:62.12-62.18" *)
  wire [1:0] Pulses;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:7.16-7.21" *)
  input Rst_n;
  wire Rst_n;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:11.22-11.25" *)
  input [2:0] Set;
  wire [2:0] Set;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:20.17-20.23" *)
  output TopPin;
  wire TopPin;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:19.17-19.21" *)
  output Zero;
  wire Zero;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:25.11-25.18" *)
  wire [9:0] _OutPos;
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:8.16-8.21" *)
  input hsClk;
  wire hsClk;
  NOT_6N16B _0_ (
    .A(Set[0]),
    .Y(InPosDek_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:85.14-88.6" *)
  BinToBcd \Reading.binToDbc  (
    .In(OutPos),
    .Out(Out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:74.10-80.2" *)
  Dekatron dekatron (
    .In_n({ 9'h1ff, InPosDek_n }),
    .Out(OutPos),
    .Pulses(Pulses),
    .Rst_n(Rst_n),
    .hsClk(hsClk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronModule.sv:66.21-72.2" *)
  DekatronPulseSender pulseSender (
    .PulseF(PulseF),
    .PulseR(PulseR),
    .Pulses(Pulses),
    .Rst_n(Rst_n),
    .hsClk(hsClk)
  );
  assign Equal = 1'hx;
  assign Nine = OutPos[9];
  assign TopPin = OutPos[5];
  assign Zero = OutPos[0];
  assign _OutPos = OutPos;
endmodule

(* src = "../DekatronPC/Dekatron/BinToBcd.v:1.1-13.10" *)
module BinToBcd(In, Out);
  wire _0_;
  wire _1_;
  (* src = "../DekatronPC/Dekatron/BinToBcd.v:3.22-3.24" *)
  input [9:0] In;
  wire [9:0] In;
  (* src = "../DekatronPC/Dekatron/BinToBcd.v:5.23-5.26" *)
  output [3:0] Out;
  wire [3:0] Out;
  OR2_N16 _2_ (
    .A(In[5]),
    .B(In[7]),
    .Y(_0_)
  );
  OR4_N16X7 _3_ (
    .A(In[3]),
    .B(In[1]),
    .C(In[9]),
    .D(_0_),
    .Y(Out[0])
  );
  OR4_N16X7 _4_ (
    .A(In[3]),
    .B(In[7]),
    .C(In[2]),
    .D(In[6]),
    .Y(Out[1])
  );
  OR2_N16 _5_ (
    .A(In[6]),
    .B(In[4]),
    .Y(_1_)
  );
  OR2_N16 _6_ (
    .A(_0_),
    .B(_1_),
    .Y(Out[2])
  );
  OR2_N16 _7_ (
    .A(In[9]),
    .B(In[8]),
    .Y(Out[3])
  );
endmodule

(* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:1.1-41.10" *)
module DekatronPulseSender(hsClk, Rst_n, PulseF, PulseR, Pulses);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:11.6-11.9" *)
  wire Dec;
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:13.6-13.10" *)
  wire OS_2;
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:14.6-14.10" *)
  wire OS_3;
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:29.6-29.14" *)
  wire PulseAny;
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:5.16-5.22" *)
  input PulseF;
  wire PulseF;
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:38.6-38.15" *)
  wire PulseLeft;
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:6.16-6.22" *)
  input PulseR;
  wire PulseR;
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:37.6-37.16" *)
  wire PulseRight;
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:7.22-7.28" *)
  output [1:0] Pulses;
  wire [1:0] Pulses;
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:4.16-4.21" *)
  input Rst_n;
  wire Rst_n;
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:15.12-15.19" *)
  wire [1:0] _Pulses;
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:3.16-3.21" *)
  input hsClk;
  wire hsClk;
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:12.6-12.8" *)
  wire pA;
  NOT_6N16B _06_ (
    .A(OS_2),
    .Y(_00_)
  );
  NOT_6N16B _07_ (
    .A(Dec),
    .Y(_01_)
  );
  OR2_N16 _08_ (
    .A(_Pulses[1]),
    .B(_Pulses[0]),
    .Y(PulseAny)
  );
  A1OOI_N16X7 _09_ (
    .A(OS_3),
    .B(_00_),
    .C(Dec),
    .Y(_02_)
  );
  NOR2_N16 _10_ (
    .A(pA),
    .B(_01_),
    .Y(_03_)
  );
  NOR2_N16 _11_ (
    .A(_02_),
    .B(_03_),
    .Y(PulseRight)
  );
  NOR2_N16 _12_ (
    .A(pA),
    .B(Dec),
    .Y(_04_)
  );
  A1OOI_N16X7 _13_ (
    .A(OS_3),
    .B(_00_),
    .C(_01_),
    .Y(_05_)
  );
  NOR2_N16 _14_ (
    .A(_04_),
    .B(_05_),
    .Y(PulseLeft)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:30.22-30.83" *)
  OneShot #(
    .DELAY(32'sd9)
  ) dir (
    .Clk(hsClk),
    .En(PulseR),
    .Impulse(Dec),
    .Rst_n(Rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:31.21-31.84" *)
  OneShot #(
    .DELAY(32'sd4)
  ) os_1 (
    .Clk(hsClk),
    .En(PulseAny),
    .Impulse(pA),
    .Rst_n(Rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:32.21-32.86" *)
  OneShot #(
    .DELAY(32'sd3)
  ) os_2 (
    .Clk(hsClk),
    .En(PulseAny),
    .Impulse(OS_2),
    .Rst_n(Rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:33.21-33.86" *)
  OneShot #(
    .DELAY(32'sd8)
  ) os_3 (
    .Clk(hsClk),
    .En(PulseAny),
    .Impulse(OS_3),
    .Rst_n(Rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:22.9-27.3" *)
  Impulse pulsesImpDec (
    .Clk(hsClk),
    .En(PulseR),
    .Impulse(_Pulses[1]),
    .Rst_n(Rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/Dekatron/DekatronPulseSender.sv:16.9-21.3" *)
  Impulse pulsesImpInc (
    .Clk(hsClk),
    .En(PulseF),
    .Impulse(_Pulses[0]),
    .Rst_n(Rst_n)
  );
  assign Pulses = { PulseRight, PulseLeft };
endmodule

(* dynports =  1  *)
(* src = "../DekatronPC/InsnLoopDetector.sv:1.1-16.10" *)
module InsnLoopDetector(Insn, LoopOpen, LoopClose);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "../DekatronPC/InsnLoopDetector.sv:2.33-2.37" *)
  input [3:0] Insn;
  wire [3:0] Insn;
  (* src = "../DekatronPC/InsnLoopDetector.sv:4.17-4.26" *)
  output LoopClose;
  wire LoopClose;
  (* src = "../DekatronPC/InsnLoopDetector.sv:3.17-3.25" *)
  output LoopOpen;
  wire LoopOpen;
  NOT_6N16B _3_ (
    .A(Insn[2]),
    .Y(_0_)
  );
  NOT_6N16B _4_ (
    .A(Insn[1]),
    .Y(_1_)
  );
  NOT_6N16B _5_ (
    .A(Insn[0]),
    .Y(_2_)
  );
  NOR4_N16 _6_ (
    .A(_0_),
    .B(Insn[3]),
    .C(_1_),
    .D(Insn[0]),
    .Y(LoopOpen)
  );
  NOR4_N16 _7_ (
    .A(_0_),
    .B(Insn[3]),
    .C(_1_),
    .D(_2_),
    .Y(LoopClose)
  );
endmodule

(* top =  1  *)
(* dynports =  1  *)
(* src = "../DekatronPC/IpLine.sv:1.1-218.10" *)
module IpLine(Rst_n, Clk, hsClk, HaltRq, dataIsZeroed, key_next_app_i, Request, Ready, IpAddress, LoopCount, RomRequest, RomReady, RomData, Insn);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  (* src = "../DekatronPC/IpLine.sv:25.11-25.17" *)
  wire [3:0] AppNum;
  (* src = "../DekatronPC/IpLine.sv:3.16-3.19" *)
  input Clk;
  wire Clk;
  (* src = "../DekatronPC/IpLine.sv:5.16-5.22" *)
  input HaltRq;
  wire HaltRq;
  (* src = "../DekatronPC/IpLine.sv:22.5-22.11" *)
  wire IP_Dec;
  (* src = "../DekatronPC/IpLine.sv:23.6-23.14" *)
  wire IP_Ready;
  (* src = "../DekatronPC/IpLine.sv:21.5-21.15" *)
  wire IP_Request;
  (* src = "../DekatronPC/IpLine.sv:18.32-18.36" *)
  output [3:0] Insn;
  wire [3:0] Insn;
  (* src = "../DekatronPC/IpLine.sv:11.54-11.63" *)
  output [19:0] IpAddress;
  wire [19:0] IpAddress;
  (* src = "../DekatronPC/IpLine.sv:12.56-12.65" *)
  output [11:0] LoopCount;
  wire [11:0] LoopCount;
  (* src = "../DekatronPC/IpLine.sv:76.6-76.19" *)
  wire LoopInsnClose;
  (* src = "../DekatronPC/IpLine.sv:66.6-66.27" *)
  wire LoopInsnCloseInternal;
  (* src = "../DekatronPC/IpLine.sv:75.6-75.18" *)
  wire LoopInsnOpen;
  (* src = "../DekatronPC/IpLine.sv:65.6-65.26" *)
  wire LoopInsnOpenInternal;
  (* src = "../DekatronPC/IpLine.sv:85.5-85.13" *)
  wire Loop_Dec;
  (* src = "../DekatronPC/IpLine.sv:87.6-87.16" *)
  wire Loop_Ready;
  (* src = "../DekatronPC/IpLine.sv:84.5-84.17" *)
  wire Loop_Request;
  (* src = "../DekatronPC/IpLine.sv:86.6-86.15" *)
  wire Loop_Zero;
  (* src = "../DekatronPC/IpLine.sv:10.17-10.22" *)
  output Ready;
  wire Ready;
  (* src = "../DekatronPC/IpLine.sv:9.16-9.23" *)
  input Request;
  wire Request;
  (* src = "../DekatronPC/IpLine.sv:16.33-16.40" *)
  input [3:0] RomData;
  wire [3:0] RomData;
  (* src = "../DekatronPC/IpLine.sv:15.16-15.24" *)
  input RomReady;
  wire RomReady;
  (* src = "../DekatronPC/IpLine.sv:14.16-14.26" *)
  output RomRequest;
  wire RomRequest;
  (* src = "../DekatronPC/IpLine.sv:2.16-2.21" *)
  input Rst_n;
  wire Rst_n;
  (* src = "../DekatronPC/IpLine.sv:7.16-7.28" *)
  input dataIsZeroed;
  wire dataIsZeroed;
  (* src = "../DekatronPC/IpLine.sv:4.16-4.21" *)
  input hsClk;
  wire hsClk;
  (* src = "../DekatronPC/IpLine.sv:8.16-8.30" *)
  input key_next_app_i;
  wire key_next_app_i;
  (* src = "../DekatronPC/IpLine.sv:26.5-26.12" *)
  wire prevApp;
  (* src = "../DekatronPC/IpLine.sv:127.11-127.16" *)
  wire [2:0] state;
  NOT_6N16B _126_ (
    .A(state[1]),
    .Y(_082_)
  );
  NOT_6N16B _127_ (
    .A(state[0]),
    .Y(_083_)
  );
  NOT_6N16B _128_ (
    .A(state[2]),
    .Y(_084_)
  );
  NOT_6N16B _129_ (
    .A(Request),
    .Y(_085_)
  );
  NOT_6N16B _130_ (
    .A(HaltRq),
    .Y(_086_)
  );
  NOT_6N16B _131_ (
    .A(RomReady),
    .Y(_087_)
  );
  NOT_6N16B _132_ (
    .A(LoopInsnClose),
    .Y(_088_)
  );
  NOT_6N16B _133_ (
    .A(Loop_Zero),
    .Y(_089_)
  );
  NOT_6N16B _134_ (
    .A(key_next_app_i),
    .Y(_090_)
  );
  NOT_6N16B _135_ (
    .A(AppNum[2]),
    .Y(_091_)
  );
  NOT_6N16B _136_ (
    .A(AppNum[0]),
    .Y(_092_)
  );
  NOT_6N16B _137_ (
    .A(IP_Dec),
    .Y(_093_)
  );
  NOT_6N16B _138_ (
    .A(Loop_Dec),
    .Y(_094_)
  );
  OR2_N16 _139_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_095_)
  );
  NOR2_N16 _140_ (
    .A(state[2]),
    .B(_095_),
    .Y(_096_)
  );
  OR2_N16 _141_ (
    .A(state[2]),
    .B(_095_),
    .Y(_097_)
  );
  NOR2_N16 _142_ (
    .A(Request),
    .B(_097_),
    .Y(Ready)
  );
  NOR2_N16 _143_ (
    .A(_090_),
    .B(prevApp),
    .Y(_098_)
  );
  OR2_N16 _144_ (
    .A(_090_),
    .B(prevApp),
    .Y(_099_)
  );
  NOR2_N16 _145_ (
    .A(_092_),
    .B(_099_),
    .Y(_100_)
  );
  NOR2_N16 _146_ (
    .A(AppNum[1]),
    .B(AppNum[0]),
    .Y(_101_)
  );
  NAND2_J2 _147_ (
    .A(_091_),
    .B(_101_),
    .Y(_102_)
  );
  NAND2_J2 _148_ (
    .A(AppNum[3]),
    .B(_102_),
    .Y(_103_)
  );
  A1OOI_N16X7 _149_ (
    .A(_098_),
    .B(_103_),
    .C(AppNum[0]),
    .Y(_104_)
  );
  NOR2_N16 _150_ (
    .A(_100_),
    .B(_104_),
    .Y(_000_)
  );
  NAND2_J2 _151_ (
    .A(AppNum[1]),
    .B(_100_),
    .Y(_105_)
  );
  NAND2_J2 _152_ (
    .A(AppNum[3]),
    .B(_098_),
    .Y(_106_)
  );
  OR2_N16 _153_ (
    .A(AppNum[1]),
    .B(_100_),
    .Y(_107_)
  );
  AND2_N16X7 _154_ (
    .A(_105_),
    .B(_107_),
    .Y(_108_)
  );
  AND2_N16X7 _155_ (
    .A(_106_),
    .B(_108_),
    .Y(_001_)
  );
  NOR2_N16 _156_ (
    .A(_091_),
    .B(_105_),
    .Y(_109_)
  );
  NAND2_J2 _157_ (
    .A(_091_),
    .B(_105_),
    .Y(_110_)
  );
  NAND2_J2 _158_ (
    .A(_106_),
    .B(_110_),
    .Y(_111_)
  );
  NOR2_N16 _159_ (
    .A(_109_),
    .B(_111_),
    .Y(_002_)
  );
  NOR2_N16 _160_ (
    .A(AppNum[3]),
    .B(_109_),
    .Y(_112_)
  );
  NOR2_N16 _161_ (
    .A(_099_),
    .B(_103_),
    .Y(_113_)
  );
  NOR2_N16 _162_ (
    .A(_112_),
    .B(_113_),
    .Y(_003_)
  );
  NOR2_N16 _163_ (
    .A(state[1]),
    .B(_083_),
    .Y(_114_)
  );
  NAND2_J2 _164_ (
    .A(_082_),
    .B(state[0]),
    .Y(_115_)
  );
  NOR2_N16 _165_ (
    .A(_086_),
    .B(_097_),
    .Y(_116_)
  );
  OR2_N16 _166_ (
    .A(state[2]),
    .B(_116_),
    .Y(_117_)
  );
  NAND2_J2 _167_ (
    .A(Request),
    .B(_086_),
    .Y(_118_)
  );
  NAND2_J2 _168_ (
    .A(_096_),
    .B(_118_),
    .Y(_119_)
  );
  NAND2_J2 _169_ (
    .A(_084_),
    .B(_119_),
    .Y(_120_)
  );
  NAND2_J2 _170_ (
    .A(state[1]),
    .B(_084_),
    .Y(_121_)
  );
  NOR2_N16 _171_ (
    .A(state[0]),
    .B(_121_),
    .Y(_122_)
  );
  NOR4_N16 _172_ (
    .A(_082_),
    .B(state[0]),
    .C(state[2]),
    .D(RomReady),
    .Y(_123_)
  );
  NOR4_N16 _173_ (
    .A(_085_),
    .B(HaltRq),
    .C(RomReady),
    .D(_097_),
    .Y(_124_)
  );
  OR2_N16 _174_ (
    .A(_123_),
    .B(_124_),
    .Y(_125_)
  );
  NAND4_N16X7 _175_ (
    .A(state[1]),
    .B(_083_),
    .C(_084_),
    .D(RomReady),
    .Y(_016_)
  );
  OR2_N16 _176_ (
    .A(LoopInsnCloseInternal),
    .B(LoopInsnOpenInternal),
    .Y(_017_)
  );
  NOR2_N16 _177_ (
    .A(Loop_Zero),
    .B(_017_),
    .Y(_018_)
  );
  NOR2_N16 _178_ (
    .A(_016_),
    .B(_018_),
    .Y(_019_)
  );
  NAND2_J2 _179_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_020_)
  );
  NOT_6N16B _180_ (
    .A(_020_),
    .Y(_021_)
  );
  AND2_N16X7 _181_ (
    .A(_089_),
    .B(_017_),
    .Y(_022_)
  );
  NOR2_N16 _182_ (
    .A(_016_),
    .B(_022_),
    .Y(_023_)
  );
  NOR2_N16 _183_ (
    .A(_087_),
    .B(_097_),
    .Y(_024_)
  );
  NAND2_J2 _184_ (
    .A(RomReady),
    .B(_096_),
    .Y(_025_)
  );
  NOR2_N16 _185_ (
    .A(_088_),
    .B(dataIsZeroed),
    .Y(_026_)
  );
  OR2_N16 _186_ (
    .A(_088_),
    .B(dataIsZeroed),
    .Y(_027_)
  );
  AND2_N16X7 _187_ (
    .A(LoopInsnOpen),
    .B(dataIsZeroed),
    .Y(_028_)
  );
  NOR4_N16 _188_ (
    .A(_118_),
    .B(_025_),
    .C(_026_),
    .D(_028_),
    .Y(_029_)
  );
  NOR4_N16 _189_ (
    .A(state[2]),
    .B(Request),
    .C(HaltRq),
    .D(_095_),
    .Y(_030_)
  );
  OR4_N16X7 _190_ (
    .A(_123_),
    .B(_124_),
    .C(_023_),
    .D(_030_),
    .Y(_031_)
  );
  OR2_N16 _191_ (
    .A(state[2]),
    .B(_020_),
    .Y(_032_)
  );
  NOT_6N16B _192_ (
    .A(_032_),
    .Y(_033_)
  );
  NOR2_N16 _193_ (
    .A(Loop_Ready),
    .B(_032_),
    .Y(_034_)
  );
  A1OOI_N16X7 _194_ (
    .A(Loop_Ready),
    .B(_022_),
    .C(_032_),
    .Y(_035_)
  );
  NOR4_N16 _195_ (
    .A(_120_),
    .B(_125_),
    .C(_019_),
    .D(_035_),
    .Y(_036_)
  );
  OR4_N16X7 _196_ (
    .A(_120_),
    .B(_125_),
    .C(_019_),
    .D(_035_),
    .Y(_037_)
  );
  NAND2_J2 _197_ (
    .A(_115_),
    .B(_036_),
    .Y(_038_)
  );
  NOR2_N16 _198_ (
    .A(_089_),
    .B(_032_),
    .Y(_039_)
  );
  NOR4_N16 _199_ (
    .A(_114_),
    .B(_027_),
    .C(_037_),
    .D(_039_),
    .Y(_040_)
  );
  A1OOI_N16X7 _200_ (
    .A(_115_),
    .B(_036_),
    .C(_093_),
    .Y(_041_)
  );
  OR2_N16 _201_ (
    .A(_040_),
    .B(_041_),
    .Y(_004_)
  );
  NAND2_J2 _202_ (
    .A(IP_Request),
    .B(_037_),
    .Y(_042_)
  );
  NAND2_J2 _203_ (
    .A(_038_),
    .B(_042_),
    .Y(_005_)
  );
  NOR2_N16 _204_ (
    .A(state[2]),
    .B(_115_),
    .Y(_043_)
  );
  NOR4_N16 _205_ (
    .A(state[1]),
    .B(_083_),
    .C(state[2]),
    .D(IP_Ready),
    .Y(_044_)
  );
  NOR4_N16 _206_ (
    .A(_120_),
    .B(_021_),
    .C(_024_),
    .D(_044_),
    .Y(_045_)
  );
  NOR2_N16 _207_ (
    .A(RomRequest),
    .B(_045_),
    .Y(_046_)
  );
  NOR2_N16 _208_ (
    .A(_122_),
    .B(_046_),
    .Y(_006_)
  );
  NOR2_N16 _209_ (
    .A(_034_),
    .B(_044_),
    .Y(_047_)
  );
  NOR2_N16 _210_ (
    .A(_084_),
    .B(_095_),
    .Y(_048_)
  );
  OR2_N16 _211_ (
    .A(_084_),
    .B(_095_),
    .Y(_049_)
  );
  NOR2_N16 _212_ (
    .A(_085_),
    .B(_049_),
    .Y(_050_)
  );
  OR2_N16 _213_ (
    .A(_123_),
    .B(_030_),
    .Y(_051_)
  );
  NOR2_N16 _214_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  OR2_N16 _215_ (
    .A(_050_),
    .B(_051_),
    .Y(_053_)
  );
  NAND2_J2 _216_ (
    .A(state[2]),
    .B(HaltRq),
    .Y(_054_)
  );
  NOR2_N16 _217_ (
    .A(_020_),
    .B(_054_),
    .Y(_055_)
  );
  NOR2_N16 _218_ (
    .A(state[0]),
    .B(_089_),
    .Y(_056_)
  );
  NOR2_N16 _219_ (
    .A(_121_),
    .B(_056_),
    .Y(_057_)
  );
  NOR4_N16 _220_ (
    .A(_116_),
    .B(_024_),
    .C(_055_),
    .D(_057_),
    .Y(_058_)
  );
  OR2_N16 _221_ (
    .A(_053_),
    .B(_058_),
    .Y(_059_)
  );
  NAND2_J2 _222_ (
    .A(_047_),
    .B(_059_),
    .Y(_007_)
  );
  NAND2_J2 _223_ (
    .A(_047_),
    .B(_052_),
    .Y(_060_)
  );
  NOR4_N16 _224_ (
    .A(HaltRq),
    .B(_087_),
    .C(_026_),
    .D(_028_),
    .Y(_061_)
  );
  OR2_N16 _225_ (
    .A(_097_),
    .B(_061_),
    .Y(_062_)
  );
  NAND2_J2 _226_ (
    .A(_122_),
    .B(_022_),
    .Y(_063_)
  );
  NAND2_J2 _227_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  NOR4_N16 _228_ (
    .A(_043_),
    .B(_055_),
    .C(_060_),
    .D(_064_),
    .Y(_065_)
  );
  A1OOI_N16X7 _229_ (
    .A(_082_),
    .B(_060_),
    .C(_065_),
    .Y(_008_)
  );
  A2OOI_N16X7 _230_ (
    .A(Loop_Zero),
    .B(_122_),
    .C(_055_),
    .D(_116_),
    .Y(_066_)
  );
  NOR2_N16 _231_ (
    .A(_060_),
    .B(_066_),
    .Y(_067_)
  );
  OR2_N16 _232_ (
    .A(_050_),
    .B(_067_),
    .Y(_009_)
  );
  NAND2_J2 _233_ (
    .A(RomData[0]),
    .B(_048_),
    .Y(_068_)
  );
  NAND2_J2 _234_ (
    .A(Insn[0]),
    .B(_049_),
    .Y(_069_)
  );
  NAND2_J2 _235_ (
    .A(_068_),
    .B(_069_),
    .Y(_010_)
  );
  NAND2_J2 _236_ (
    .A(RomData[1]),
    .B(_048_),
    .Y(_070_)
  );
  NAND2_J2 _237_ (
    .A(Insn[1]),
    .B(_049_),
    .Y(_071_)
  );
  NAND2_J2 _238_ (
    .A(_070_),
    .B(_071_),
    .Y(_011_)
  );
  NAND2_J2 _239_ (
    .A(RomData[2]),
    .B(_048_),
    .Y(_072_)
  );
  NAND2_J2 _240_ (
    .A(Insn[2]),
    .B(_049_),
    .Y(_073_)
  );
  NAND2_J2 _241_ (
    .A(_072_),
    .B(_073_),
    .Y(_012_)
  );
  NAND2_J2 _242_ (
    .A(RomData[3]),
    .B(_048_),
    .Y(_074_)
  );
  NAND2_J2 _243_ (
    .A(Insn[3]),
    .B(_049_),
    .Y(_075_)
  );
  NAND2_J2 _244_ (
    .A(_074_),
    .B(_075_),
    .Y(_013_)
  );
  NOR4_N16 _245_ (
    .A(state[0]),
    .B(_117_),
    .C(_029_),
    .D(_031_),
    .Y(_076_)
  );
  OR2_N16 _246_ (
    .A(LoopInsnOpenInternal),
    .B(_027_),
    .Y(_077_)
  );
  OR2_N16 _247_ (
    .A(LoopInsnCloseInternal),
    .B(_026_),
    .Y(_078_)
  );
  NAND4_N16X7 _248_ (
    .A(_122_),
    .B(_076_),
    .C(_077_),
    .D(_078_),
    .Y(_079_)
  );
  OR2_N16 _249_ (
    .A(_094_),
    .B(_076_),
    .Y(_080_)
  );
  NAND2_J2 _250_ (
    .A(_079_),
    .B(_080_),
    .Y(_014_)
  );
  NOR2_N16 _251_ (
    .A(Loop_Request),
    .B(_076_),
    .Y(_081_)
  );
  NOR2_N16 _252_ (
    .A(_033_),
    .B(_081_),
    .Y(_015_)
  );
  (* src = "../DekatronPC/IpLine.sv:28.1-43.4" *)
  DFFSR_n _253_ (
    .C(Clk),
    .D(_000_),
    .Q(AppNum[0]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:28.1-43.4" *)
  DFFSR_n _254_ (
    .C(Clk),
    .D(_001_),
    .Q(AppNum[1]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:28.1-43.4" *)
  DFFSR_n _255_ (
    .C(Clk),
    .D(_002_),
    .Q(AppNum[2]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:28.1-43.4" *)
  DFFSR_n _256_ (
    .C(Clk),
    .D(_003_),
    .Q(AppNum[3]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:129.1-216.4" *)
  DFFSR_n _257_ (
    .C(Clk),
    .D(_004_),
    .Q(IP_Dec),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:129.1-216.4" *)
  DFFSR_n _258_ (
    .C(Clk),
    .D(_005_),
    .Q(IP_Request),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:129.1-216.4" *)
  DFFSR_n _259_ (
    .C(Clk),
    .D(_006_),
    .Q(RomRequest),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:129.1-216.4" *)
  DFFSR_n _260_ (
    .C(Clk),
    .D(_007_),
    .Q(state[0]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:129.1-216.4" *)
  DFFSR_n _261_ (
    .C(Clk),
    .D(_008_),
    .Q(state[1]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:129.1-216.4" *)
  DFFSR_n _262_ (
    .C(Clk),
    .D(_009_),
    .Q(state[2]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:129.1-216.4" *)
  DFFSR_n _263_ (
    .C(Clk),
    .D(_010_),
    .Q(Insn[0]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:129.1-216.4" *)
  DFFSR_n _264_ (
    .C(Clk),
    .D(_011_),
    .Q(Insn[1]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:129.1-216.4" *)
  DFFSR_n _265_ (
    .C(Clk),
    .D(_012_),
    .Q(Insn[2]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:129.1-216.4" *)
  DFFSR_n _266_ (
    .C(Clk),
    .D(_013_),
    .Q(Insn[3]),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:28.1-43.4" *)
  DFFSR_n _267_ (
    .C(Clk),
    .D(key_next_app_i),
    .Q(prevApp),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:129.1-216.4" *)
  DFFSR_n _268_ (
    .C(Clk),
    .D(_014_),
    .Q(Loop_Dec),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:129.1-216.4" *)
  DFFSR_n _269_ (
    .C(Clk),
    .D(_015_),
    .Q(Loop_Request),
    .R(Rst_n),
    .S(1'h0)
  );
  (* src = "../DekatronPC/IpLine.sv:48.14-62.14" *)
  \$paramod\DekatronCounter\D_NUM=32'00000000000000000000000000000100\WRITE=1'0  IP_counter (
    .Clk(Clk),
    .Dec(IP_Dec),
    .In(16'h0000),
    .Out(IpAddress[15:0]),
    .Ready(IP_Ready),
    .Request(IP_Request),
    .Rst_n(Rst_n),
    .Set(1'h0),
    .SetZero(1'h0),
    .hsClk(hsClk)
  );
  (* src = "../DekatronPC/IpLine.sv:99.14-113.14" *)
  \$paramod\DekatronCounter\D_NUM=4'0011\READ=1'0\WRITE=1'0  Loop_counter (
    .Clk(Clk),
    .Dec(Loop_Dec),
    .In(12'h000),
    .Out(LoopCount),
    .Ready(Loop_Ready),
    .Request(Loop_Request),
    .Rst_n(Rst_n),
    .Set(1'h0),
    .SetZero(1'h0),
    .Zero(Loop_Zero),
    .hsClk(hsClk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/IpLine.sv:78.18-82.2" *)
  InsnLoopDetector insnLoopDetector (
    .Insn(Insn),
    .LoopClose(LoopInsnClose),
    .LoopOpen(LoopInsnOpen)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../DekatronPC/IpLine.sv:68.18-72.2" *)
  InsnLoopDetector insnLoopDetectorInternal (
    .Insn(RomData),
    .LoopClose(LoopInsnCloseInternal),
    .LoopOpen(LoopInsnOpenInternal)
  );
  assign IpAddress[19:16] = AppNum;
endmodule
