"""
Tests for Dekatron — dekatron tube glow model.

Internal 30-bit Cathodes register drives 10-bit Out:
  Out[0]=Cathodes[0],  Out[1]=Cathodes[3],  Out[2]=Cathodes[6],
  Out[3]=Cathodes[9],  Out[4]=Cathodes[12], Out[5]=Cathodes[15],
  Out[6]=Cathodes[18], Out[7]=Cathodes[21], Out[8]=Cathodes[24],
  Out[9]=Cathodes[27]

Guide cathodes (right): 1,4,7,10,13,16,19,22,25,28
Guide cathodes (left):  2,5,8,11,14,17,20,23,26,29

Stepping requires a multi-cycle pulse sequence as generated by
DekatronPulseSender. The Dekatron uses two-phase pulsing:
  Pulses[0] and Pulses[1] fire in sequence to advance through
  Main → Guide → Guide → Main.
"""

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import Timer, RisingEdge

import logging
log = logging.getLogger(__name__)

HS_CLK_PERIOD = 100  # ns


def _which_out(dut) -> int:
    """Return the index (0-9) of the active output, or -1 if none."""
    val = int(dut.Out.value)
    for i in range(10):
        if val & (1 << i):
            return i
    return -1


def _out_onehot(dut) -> int:
    """Return the Out value as integer."""
    return int(dut.Out.value)


@cocotb.test()
async def test_dekatron_reset(dut):
    """Dekatron: after reset, Out[0]=1 (glow at position 0)."""
    clock = Clock(dut.hsClk, HS_CLK_PERIOD, unit="ns")
    cocotb.start_soon(clock.start())

    dut.Rst_n.value = 0
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Rst_n.value = 1
    for _ in range(3):
        await RisingEdge(dut.hsClk)

    out_val = _out_onehot(dut)
    pos = _which_out(dut)
    assert pos == 0, f"After reset expected Out[0]=1, got Out=0b{out_val:010b} (position {pos})"
    assert bin(out_val).count("1") == 1, (
        f"Expected exactly one output bit set after reset, got 0b{out_val:010b}"
    )


@cocotb.test()
async def test_dekatron_write_position(dut):
    """Dekatron: write to position 5 via In_n with Pulses[0]=1."""
    clock = Clock(dut.hsClk, HS_CLK_PERIOD, unit="ns")
    cocotb.start_soon(clock.start())

    dut.Rst_n.value = 0
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Rst_n.value = 1
    for _ in range(3):
        await RisingEdge(dut.hsClk)

    pos = _which_out(dut)
    assert pos == 0, f"After reset expected position 0, got {pos}"

    dut.In_n.value = (~(1 << 5)) & 0x3FF
    dut.Pulses.value = 1
    await RisingEdge(dut.hsClk)
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    await RisingEdge(dut.hsClk)

    pos = _which_out(dut)
    assert pos == 5, f"After write to position 5 expected Out[5]=1, got position {pos}"


@cocotb.test()
async def test_dekatron_step_right(dut):
    """Dekatron: step right from position 0 using two-phase pulse sequence."""
    clock = Clock(dut.hsClk, HS_CLK_PERIOD, unit="ns")
    cocotb.start_soon(clock.start())

    dut.Rst_n.value = 0
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Rst_n.value = 1
    for _ in range(3):
        await RisingEdge(dut.hsClk)

    pos_before = _which_out(dut)
    assert pos_before == 0, f"After reset expected position 0, got {pos_before}"

    # Step right: forward stepping uses Pulses[0]=1 first, then Pulses[1]=1.
    dut.Pulses.value = 1  # Pulses[0]=1, Pulses[1]=0
    for _ in range(5):
        await RisingEdge(dut.hsClk)

    dut.Pulses.value = 2  # Pulses[1]=1, Pulses[0]=0
    for _ in range(5):
        await RisingEdge(dut.hsClk)

    dut.Pulses.value = 0
    for _ in range(10):
        await RisingEdge(dut.hsClk)

    pos_after = _which_out(dut)
    assert pos_after != pos_before, (
        f"Position should change after stepping right, was {pos_before}, still {pos_after}"
    )


@cocotb.test()
async def test_dekatron_step_left(dut):
    """Dekatron: step left from position 0 using two-phase pulse sequence."""
    clock = Clock(dut.hsClk, HS_CLK_PERIOD, unit="ns")
    cocotb.start_soon(clock.start())

    dut.Rst_n.value = 0
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Rst_n.value = 1
    for _ in range(3):
        await RisingEdge(dut.hsClk)

    pos_before = _which_out(dut)
    assert pos_before == 0, f"After reset expected position 0, got {pos_before}"

    # Step left: reverse stepping uses Pulses[1]=1 first, then Pulses[0]=1
    dut.Pulses.value = 2  # Pulses[1]=1, Pulses[0]=0
    for _ in range(5):
        await RisingEdge(dut.hsClk)

    dut.Pulses.value = 1  # Pulses[0]=1, Pulses[1]=0
    for _ in range(5):
        await RisingEdge(dut.hsClk)

    dut.Pulses.value = 0
    for _ in range(10):
        await RisingEdge(dut.hsClk)

    pos_after = _which_out(dut)
    assert pos_after != pos_before, (
        f"Position should change after stepping left, was {pos_before}, still {pos_after}"
    )


@cocotb.test()
async def test_dekatron_step_right_left_returns(dut):
    """Dekatron: step right then left returns to original position."""
    clock = Clock(dut.hsClk, HS_CLK_PERIOD, unit="ns")
    cocotb.start_soon(clock.start())

    dut.Rst_n.value = 0
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Rst_n.value = 1
    for _ in range(3):
        await RisingEdge(dut.hsClk)

    original = _which_out(dut)
    assert original == 0, f"After reset expected position 0, got {original}"

    # Step right: Pulses[0]=1 first, then Pulses[1]=1
    dut.Pulses.value = 1
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Pulses.value = 2
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Pulses.value = 0
    for _ in range(10):
        await RisingEdge(dut.hsClk)

    right_pos = _which_out(dut)
    log.info(f"After step right: position {right_pos}")

    # Step left: Pulses[1]=1 first, then Pulses[0]=1
    dut.Pulses.value = 2
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Pulses.value = 1
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Pulses.value = 0
    for _ in range(10):
        await RisingEdge(dut.hsClk)

    final = _which_out(dut)
    assert final == original, (
        f"Step right then left should return to original position {original}, got {final}"
    )


@cocotb.test()
async def test_dekatron_write_all_positions(dut):
    """Dekatron: write to every position 0-9 and verify."""
    clock = Clock(dut.hsClk, HS_CLK_PERIOD, unit="ns")
    cocotb.start_soon(clock.start())

    dut.Rst_n.value = 0
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Rst_n.value = 1
    for _ in range(3):
        await RisingEdge(dut.hsClk)

    for target_pos in range(10):
        dut.In_n.value = (~(1 << target_pos)) & 0x3FF
        dut.Pulses.value = 1
        await RisingEdge(dut.hsClk)
        dut.Pulses.value = 0
        dut.In_n.value = 0x3FF
        await RisingEdge(dut.hsClk)

        pos = _which_out(dut)
        assert pos == target_pos, (
            f"Write to position {target_pos}: expected Out[{target_pos}]=1, got Out[{pos}]=1"
        )


@cocotb.test()
async def test_dekatron_multiple_steps_right(dut):
    """Dekatron: step right multiple positions, verify position changes."""
    clock = Clock(dut.hsClk, HS_CLK_PERIOD, unit="ns")
    cocotb.start_soon(clock.start())

    dut.Rst_n.value = 0
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Rst_n.value = 1
    for _ in range(3):
        await RisingEdge(dut.hsClk)

    positions_seen = {_which_out(dut)}

    for step in range(5):
        # Two-phase right step: Pulses[0]=1 first, then Pulses[1]=1
        dut.Pulses.value = 1
        for _ in range(5):
            await RisingEdge(dut.hsClk)
        dut.Pulses.value = 2
        for _ in range(5):
            await RisingEdge(dut.hsClk)
        dut.Pulses.value = 0
        for _ in range(8):
            await RisingEdge(dut.hsClk)

        pos = _which_out(dut)
        positions_seen.add(pos)
        log.info(f"After step {step + 1}: position {pos}")

    assert len(positions_seen) > 1, (
        f"Stepping should change position, seen only: {positions_seen}"
    )


@cocotb.test()
async def test_dekatron_wraparound(dut):
    """Dekatron: stepping eventually wraps around the 10-position ring."""
    clock = Clock(dut.hsClk, HS_CLK_PERIOD, unit="ns")
    cocotb.start_soon(clock.start())

    dut.Rst_n.value = 0
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Rst_n.value = 1
    for _ in range(3):
        await RisingEdge(dut.hsClk)

    # Write to position 9
    dut.In_n.value = (~(1 << 9)) & 0x3FF
    dut.Pulses.value = 1
    await RisingEdge(dut.hsClk)
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    await RisingEdge(dut.hsClk)

    pos = _which_out(dut)
    assert pos == 9, f"After write to 9 expected position 9, got {pos}"

    # Step right (forward) from 9: Pulses[0]=1 first, then Pulses[1]=1
    dut.Pulses.value = 1
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Pulses.value = 2
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Pulses.value = 0
    for _ in range(10):
        await RisingEdge(dut.hsClk)

    pos = _which_out(dut)
    # After stepping right past position 9, expect wraparound to position 0
    assert pos == 0, f"After stepping right from 9 expected wrap to 0, got {pos}"


@cocotb.test()
async def test_dekatron_no_pulse_no_change(dut):
    """Dekatron: no Pulses, no write → output holds."""
    clock = Clock(dut.hsClk, HS_CLK_PERIOD, unit="ns")
    cocotb.start_soon(clock.start())

    dut.Rst_n.value = 0
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Rst_n.value = 1
    for _ in range(3):
        await RisingEdge(dut.hsClk)

    pos_before = _which_out(dut)

    for _ in range(20):
        await RisingEdge(dut.hsClk)

    pos_after = _which_out(dut)
    assert pos_after == pos_before, (
        f"Position should hold with no pulses, was {pos_before}, now {pos_after}"
    )


@cocotb.test()
async def test_dekatron_write_overrides_step(dut):
    """Dekatron: write operation takes priority over stepping."""
    clock = Clock(dut.hsClk, HS_CLK_PERIOD, unit="ns")
    cocotb.start_soon(clock.start())

    dut.Rst_n.value = 0
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Rst_n.value = 1
    for _ in range(3):
        await RisingEdge(dut.hsClk)

    # Write to position 3 first
    dut.In_n.value = (~(1 << 3)) & 0x3FF
    dut.Pulses.value = 1
    await RisingEdge(dut.hsClk)
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    await RisingEdge(dut.hsClk)

    pos = _which_out(dut)
    assert pos == 3, f"Expected position 3 after write, got {pos}"

    # Now write to position 7 while pulsing (write overrides step)
    dut.In_n.value = (~(1 << 7)) & 0x3FF
    dut.Pulses.value = 2  # Step right pulse active
    await RisingEdge(dut.hsClk)
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    await RisingEdge(dut.hsClk)

    pos = _which_out(dut)
    assert pos == 7, f"Write should override step, expected 7, got {pos}"


@cocotb.test()
async def test_dekatron_write_no_pulse(dut):
    """Dekatron: write with In_n active but no pulse still overwrites."""
    clock = Clock(dut.hsClk, HS_CLK_PERIOD, unit="ns")
    cocotb.start_soon(clock.start())

    dut.Rst_n.value = 0
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Rst_n.value = 1
    for _ in range(3):
        await RisingEdge(dut.hsClk)

    # Set In_n to write to position 2 with pulse
    dut.In_n.value = (~(1 << 2)) & 0x3FF
    dut.Pulses.value = 1
    await RisingEdge(dut.hsClk)
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    await RisingEdge(dut.hsClk)

    pos = _which_out(dut)
    assert pos == 2, (
        f"Write to position 2: expected position 2, got {pos}"
    )


@cocotb.test()
async def test_dekatron_reset_clears_state(dut):
    """Dekatron: reset during operation returns to position 0."""
    clock = Clock(dut.hsClk, HS_CLK_PERIOD, unit="ns")
    cocotb.start_soon(clock.start())

    dut.Rst_n.value = 0
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    for _ in range(5):
        await RisingEdge(dut.hsClk)
    dut.Rst_n.value = 1
    for _ in range(3):
        await RisingEdge(dut.hsClk)

    # Write to position 5
    dut.In_n.value = (~(1 << 5)) & 0x3FF
    dut.Pulses.value = 1
    await RisingEdge(dut.hsClk)
    dut.Pulses.value = 0
    dut.In_n.value = 0x3FF
    await RisingEdge(dut.hsClk)

    pos = _which_out(dut)
    assert pos == 5, f"After write expected position 5, got {pos}"

    # Assert reset
    dut.Rst_n.value = 0
    for _ in range(3):
        await RisingEdge(dut.hsClk)
    dut.Rst_n.value = 1
    for _ in range(3):
        await RisingEdge(dut.hsClk)

    pos = _which_out(dut)
    assert pos == 0, f"After reset expected position 0, got {pos}"
